### ISSUE TITLE
Support static configuration reader

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#180]
Declarative Components (and other parts of OSGi) can be consigured using configurationadmin server. While it is always possible to supply such configuration by code or by management console, we should provide a way that chemclipse can read it from config files located in the file-system.

**Comment by eselmeister** [comment]
Yep, that's a good idea to provide a default/system mechanism, so that specific configurations can be added.Am 22.12.2019 05:59 schrieb Christoph Läubrich <notifications@github.com>:Declarative Components (and other parts of OSGi) can be consigured using configurationadmin server. While it is always possible to supply such configuration by code or by management console, we should provide a way that chemclipse can read it from config files located in the file-system.
