### ISSUE TITLE
Remove org.eclipse.chemclipse.model.core.IScan.getIdentifier()

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#189]
The method is only used by the nist to temporary store an identifier that can be used to back-trace a scan after identification. This can better be archived by an internal Map instead of polluting the interface with implementation details.

**Comment by kerner1000** [comment]
+1

**Comment by eselmeister** [comment]
Please double check if this is also used by the File Identifier. If it is only used by the NIST connector, than it can be removed if the NIST connector handles the assignment differently.Am 03.01.2020 19:21 schrieb Christoph Läubrich <notifications@github.com>:The method is only used by the nist to temporary store an identifier that can be used to back-trace a scan after identification. This can better be archived by an internal Map instead of polluting the interface with implementation details.
