### ISSUE TITLE
PCA - sample list focusing wrong entry

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#1962]
If the sample list contains "Samples Names" with the same content, then the selection of the 2nd, 3rd ... row fails and  focus is immediately set to the first row with the selected name.
 
[Demo.zip](https://github.com/user-attachments/files/17804130/Demo.zip)

![Screenshot From 2024-11-18 18-20-27](https://github.com/user-attachments/assets/8bfed50a-5ef0-428e-b067-411de22b3c0e)
![Screenshot From 2024-11-18 18-20-54](https://github.com/user-attachments/assets/e2bf80fb-142c-4d38-bf8e-c818411fdab6)
![Screenshot From 2024-11-18 18-21-13](https://github.com/user-attachments/assets/1c0ddfac-d3fb-4e23-b62a-e355c9e2e206)
![Screenshot From 2024-11-18 18-21-20](https://github.com/user-attachments/assets/fee343ca-f591-449c-9003-06f3f28c9d03)

**Comment by lorenzgerber** [comment]
The problem is not based on the sample selection/highlighting but on the underlying classes representing samples in the result element. One cause is an equals method based on sample name and in another cause is the series converter translating sample names into series ids. I will suggest a solution.
