### ISSUE TITLE
Peak/Scan List scrolls to top when selecting multiple entries

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#986]
which is annoying. Doesn't happen on a single selection.

**Comment by eselmeister** [comment]
On my machine, it also occurs on single selection.

1. Load a chromatogram, so that the number listed peak entries exceeds the available space in the peak list
2. Scroll down into the previously hidden entries
3. Select a peak
4. Then it is marked correctly in the chromatogram, but the list scrolls to top
